### ISSUE TITLE
🐛 Bug: Space in folder name causes error

### ISSUE THREAD

**Issue by sidielnikov** [Kryptor-Software/Kryptor#37]
Hi, found a bug associated with a space in a folder for encryption

### Screenshot
https://filen.io/f/f372031e-ff10-4209-8d7b-bb24fbc4e9c1#!yQqtNzQtbQfbmUCaHRr5pRFgZfIPR6gq

### Platform info
 - OS: [e.g. Windows 7]
 - Kryptor version: [e.g. v3.1.0]

**Comment by samuel-lucas6** [comment]
Hi again @sidielnikov, I see what's going on now. You need to specify "speech marks" around file names/paths that contain a space, as explained [here](https://www.kryptor.co.uk/tutorial#specifying-files). That should solve your issue, so I'm going to close this.
