### ISSUE TITLE
🐛Bug: cannot execute pre-built Linux binary; exec: Failed to execute process

### ISSUE THREAD

**Issue by NoelGisler** [Kryptor-Software/Kryptor#59]
### Description
cannot execute the linux binary blob

Fish Log:
exec: Failed to execute process '/home/[profile redacted]/.nix-profile/bin/kryptor': The file exists and is executable. Check the interpreter or linker?
Bash Log:
bash: ./kryptor: cannot execute: required file not found

### Steps to reproduce
1. download Linux Pre-built binary
2. chmod +x it
3. try to run it
4. get error log

### Expected behaviour
it should run and tell me to use -h

### Platform info
 - OS: [NixOS unstable]
 - Kryptor version: [4.0.1]

**Comment by samuel-lucas6** [comment]
Hmm. Are you using the x64 or ARM64 version? I don't know anything about NixOS, but it doesn't look like it's an [officially supported](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md) Linux distro for .NET, so maybe the self-contained publish doesn't work with it.

**Comment by samuel-lucas6** [comment]
@Neon-44 Any update on this? Otherwise, I will close this issue, and you can reopen it if needed.

**Comment by NoelGisler** [comment]
hmm, i could have sworn i already commented on here, but whatever.

i assume it doesn't work because NixOS uses the Nix Packaging Format and throws over board the File Hierarchy System.
we do have Tools like Patchelf but for some reason they don't work on Kryptor.
i can however run it with steam-run, indicating that the problem does indeed lie with NixOS and FHS

Building dotNet Packages from source is a feature that is technically there but not currently in a workable state from what i can see

so i guess i can't package the binary because of dependencies needed in the binary, but i also can't build it from source because the NixOS tooling isn't there yet.

if you don't have any other ideas i guess you can close the issue and i'll reopen once the dotNet tooling is in a working state. if there are any problems of course, otherwise i'll just package it and notify you about my success.
